### PR TITLE
fix "FieldError: Unknown field(s) (username) specified for User"

### PR DESCRIPTION
**Pull request by imposeren**
When usermodel have 'USERNAME_FIELD' different from 'username' then importing any signup flow will result in exception: 
```python
    # ... try to import Signup flows and/or form:
    from sitegate.signup_flows.modern import ModernSignup, ModernSignupForm
  File "/home/imposeren/.virtualenvs/tabletop/local/lib/python2.7/site-packages/sitegate/signup_flows/modern.py", line 6, in <module>
    from .classic import SimpleClassicWithEmailSignup, SimpleClassicWithEmailSignupForm
  File "/home/imposeren/.virtualenvs/tabletop/local/lib/python2.7/site-packages/sitegate/signup_flows/classic.py", line 15, in <module>
    class ClassicSignupForm(UserCreationForm):
  File "/home/imposeren/.virtualenvs/tabletop/local/lib/python2.7/site-packages/django/forms/models.py", line 295, in __new__
    raise FieldError(message)

django.core.exceptions.FieldError: Unknown field(s) (username) specified for User
```

this pull request will fix this

### CODE REVIEW

**Comment by idlesign** [comment]
Thank you. 
I'll try to review it in a couple of days.

**Comment by idlesign** [comment]
That'll do. 
Merged.

**Comment by imposeren** [comment]
Can you publish new version on PyPI?

**Comment by idlesign** [comment]
Done. 0.10.2

**Pull request merged**
