### PR TITLE
confirming email changes

### PR DESCRIPTION
**Pull request by imposeren**
I think that it's good to have ability to validate email changes with same model and view that are used to confirm emails on registration. This pull request adds easy way to do so with docs. For default config nothing will change: developers should provide their own methods to generate required DB rows and emails

### CODE REVIEW

**Comment by imposeren** [comment]
JFYI:
I have not added any tests for new features. I do not know why coverage increased (it' something obvious but I do not want to investigate)

**Comment by idlesign** [comment]
Thank you for your participation %)
I'd review it in a few days.

**Comment by imposeren** [comment]
There may be several more universal alternatives:

1. ``signing.dumps(...)`` as code:
   1. increase length of "code" field
   2. store ``signing.dumps(arbitrary_data)`` in code field
   3. it's now possible to use "new_email" field without actual field by decrypting data in code field

2. zero changes to models, just use "special" urls with encrypted data salted by email_confirmation.code:
   1. here we do not add any changes to models
   2. instead we just create special view something like ``"^/custom-confirmations/(?P<code_pk>\d+)/(?P<data>\S+)/$"``
   3. to generate url we'll use ``signing.dumps(data, salt=code.code)`` (that's why i use code_pk instead of code in url above)
   4. we now can perform any confirmations with a single view and old model. This also will make it easier to send confirmation emails both to new and old email addresses (to old: "do you really want to change email to XXX?", to new: "To confirm that this email belongs to owner of OLD_EMAIL pplease follow next link...")
      ```
code = get_object_or_404(EmailConfirmation, pk=code_pk, expired=False)
data = signing.loads(data, salt=code.code)
```

3. Currently proposed changes are used in my project without sending confirmations to old email addresses (just to new one). I have many users with dead emails: they are registered with python-social-auth through vk.com backend and many of them just don't use old mailbox anymore or their mailbox is already dead.

**Comment by idlesign** [comment]
Universal alternatives are always more welcome.
No 2 sounds interesting. I'm taking a time out to think over that. 
Please inform me if any new ideas.

**Pull request closed without merging**
